### ISSUE TITLE
Hi excuse me, I have other question about this loss function.

### ISSUE THREAD

**Issue by gentlezr** [mmmmimic/Topo-Loss#3]
1. At line64: https://github.com/mmmmimic/Topo-Loss/blob/e1abd2fcdcfdb7456f1cb56a89fe796e75a28cbc/loss.py#L64，the tensor index +1 [b, idx+1, ...] may mean you ignore the background of pred but the index of topo_label doen't plus one. It looks that in your loss function's input the pred include background and the topo_label doesn't contain background topo.  If it's true, please modify the comment of forward().
2. I compare your codes with the official example and find that the compute methods of l1 on line80 are equal but different about l0 on line74. could you please tell me why about this?
3. It seems topologylayer includes a minor optimizer process it may change the parameters of Demonet, so you add a MSE term(  l_sqdiff) between old model output and new model output to alleviate it?
Waiting for your reply and give you my appreciation.

**Comment by mmmmimic** [comment]
Hi!
1. Yes you are right. I have modified the comment. Sorry for the confusion - the code was released a year ago and I have forgotten the details. 
2. I think we should also consider bar signs for connected components, according to equation (3) in the paper.  
3. If I understand the paper correctly, yes you are right (Eq. 5 in the paper).

**Comment by gentlezr** [comment]
Thanks for your explanation. Have a good time to you.
